language: cpp
compiler: gcc
dist: trusty

before_install:
  # C11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C11
  #- sudo apt-get install -qq g++-5
  #- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90


script: 
  - qmake
  - make
  - ./travis_qmake_gcc_c11
